# Generated by Django 2.2.5 on 2020-03-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commuters', '0016_auto_20200321_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('document', models.ImageField(upload_to='commuter_documents')),
                ('commuter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commuters.Commuters')),
            ],
        ),
    ]
