# Generated by Django 2.2.5 on 2020-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200322_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='commuter_documents/'),
        ),
    ]
