# Generated by Django 2.2.5 on 2020-03-27 09:40

from django.db import migrations, models
import documents.validator


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200322_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='commuter_documents/', validators=[documents.validator.file_size]),
        ),
    ]
