# Generated by Django 2.2.5 on 2020-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200327_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='commuter_documents/'),
        ),
    ]
