# Generated by Django 2.2.5 on 2020-04-03 16:08

from django.db import migrations, models
import documents.validator


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200403_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='commuter_documents/', validators=[documents.validator.file_size]),
        ),
    ]
