# Generated by Django 2.2.5 on 2020-03-22 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_cities_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
