# Generated by Django 2.2.5 on 2020-03-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20200322_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='major_announcement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='minor_announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
