# Generated by Django 2.2.5 on 2020-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20200323_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='major_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='minor_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
