# Generated by Django 2.2.5 on 2020-03-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20200323_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='cities.Provinces'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='city', to=settings.AUTH_USER_MODEL),
        ),
    ]
