# Generated by Django 2.2.5 on 2020-03-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commuters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_city', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('profession', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('company_location', models.CharField(max_length=256)),
                ('present_address', models.CharField(max_length=256)),
                ('permanent_address', models.CharField(max_length=256)),
                ('cell_number', models.CharField(blank=True, max_length=32)),
                ('tele_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lives_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuters', to='cities.Cities')),
            ],
        ),
    ]
