# Generated by Django 2.2.5 on 2020-03-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0015_auto_20200320_0644'),
        ('commuters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commuter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_routes', to='commuters.Commuters')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_routes', to='transportations.Routes')),
            ],
        ),
    ]
