# Generated by Django 2.2.5 on 2020-03-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0007_auto_20200320_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuters',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commuter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
