# Generated by Django 2.2.5 on 2020-03-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0008_auto_20200320_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commuters',
            name='works_city',
        ),
    ]
