# Generated by Django 2.2.5 on 2020-03-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('commuters', '0011_commuters_province_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commuters',
            name='province_id',
        ),
        migrations.AddField(
            model_name='commuters',
            name='lives_province_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commuters', to='cities.Provinces'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commuters',
            name='works_province_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='cities.Provinces'),
            preserve_default=False,
        ),
    ]
