# Generated by Django 2.2.5 on 2020-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0012_auto_20200321_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuters',
            name='comments',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='commuters',
            name='preferred_pick_up',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
