# Generated by Django 2.2.5 on 2020-03-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0015_auto_20200321_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuters',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commuter', to=settings.AUTH_USER_MODEL),
        ),
    ]
