# Generated by Django 2.2.5 on 2020-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0016_auto_20200321_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_routes',
            name='status',
            field=models.CharField(choices=[('A', 'Allowed'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=512),
        ),
    ]
