# Generated by Django 2.2.5 on 2020-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0017_allowed_routes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_routes',
            name='requested_at',
            field=models.DateField(auto_now=True),
        ),
    ]
