# Generated by Django 2.2.5 on 2020-03-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0018_allowed_routes_requested_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowed_routes',
            name='requested_at',
        ),
    ]
