# Generated by Django 2.2.5 on 2020-03-23 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0019_remove_allowed_routes_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_routes',
            name='requested_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
