# Generated by Django 2.2.5 on 2020-03-27 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0022_auto_20200325_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_routes',
            name='commuter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_routes', to='commuters.Commuters'),
        ),
        migrations.AlterField(
            model_name='allowed_routes',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_routes', to='employees.Employees'),
        ),
        migrations.AlterField(
            model_name='allowed_routes',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_routes', to='transportations.Routes'),
        ),
        migrations.AlterField(
            model_name='commuters',
            name='lives_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commuters', to='cities.Cities'),
        ),
        migrations.AlterField(
            model_name='commuters',
            name='lives_province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commuters', to='cities.Provinces'),
        ),
        migrations.AlterField(
            model_name='commuters',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commuter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commuters',
            name='works_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='cities.Cities'),
        ),
        migrations.AlterField(
            model_name='commuters',
            name='works_province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='cities.Provinces'),
        ),
    ]
