# Generated by Django 2.2.5 on 2020-03-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0023_auto_20200327_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_routes',
            name='commuter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_routes', to='commuters.Commuters'),
        ),
        migrations.AlterField(
            model_name='allowed_routes',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_routes', to='employees.Employees'),
        ),
        migrations.AlterField(
            model_name='allowed_routes',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_routes', to='transportations.Routes'),
        ),
    ]
