# Generated by Django 2.2.5 on 2020-03-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0024_auto_20200327_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_routes',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_routes', to='employees.Employees'),
        ),
    ]
