# Generated by Django 2.2.5 on 2020-03-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=256)),
                ('start_location', models.CharField(max_length=128)),
                ('start_city', models.CharField(max_length=64)),
                ('end_location', models.CharField(max_length=128)),
                ('end_city', models.CharField(max_length=64)),
                ('vehicle', models.CharField(max_length=64)),
                ('carry_capacity', models.IntegerField()),
                ('active', models.BooleanField()),
                ('duration_hours', models.FloatField()),
                ('going', models.CharField(choices=[('GI', 'Going Into The City'), ('GO', 'Going Out of The City'), ('SI', 'Staying In The City')], default='SI', max_length=20)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='cities.Cities')),
            ],
        ),
    ]
