# Generated by Django 2.2.5 on 2020-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportations',
            name='carry_capacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportations',
            name='duration_hours',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportations',
            name='vehicle',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
