# Generated by Django 2.2.5 on 2020-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0005_auto_20200319_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportations',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
