# Generated by Django 2.2.5 on 2020-03-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0006_auto_20200319_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportations',
            name='carry_capacity',
        ),
    ]
