# Generated by Django 2.2.5 on 2020-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0007_remove_transportations_carry_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
    ]
