# Generated by Django 2.2.5 on 2020-03-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('transportations', '0009_auto_20200319_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transportations',
            new_name='Directions',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='transportation_id',
            new_name='direction_id',
        ),
        migrations.AlterUniqueTogether(
            name='times',
            unique_together={('direction_id', 'time')},
        ),
    ]
