# Generated by Django 2.2.5 on 2020-03-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0011_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directions',
            name='city_id',
        ),
        migrations.AddField(
            model_name='directions',
            name='route_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='transportations.Routes'),
            preserve_default=False,
        ),
    ]
