# Generated by Django 2.2.5 on 2020-03-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0012_auto_20200320_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='transportations.Routes'),
        ),
    ]
