# Generated by Django 2.2.5 on 2020-03-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('transportations', '0013_auto_20200320_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directions',
            name='end_city',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='going',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='road',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='route',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='start_city',
        ),
        migrations.AddField(
            model_name='routes',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='cities.Cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routes',
            name='via',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
