# Generated by Django 2.2.5 on 2020-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0014_auto_20200320_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directions',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='directions',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
