# Generated by Django 2.2.5 on 2020-03-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('transportations', '0015_auto_20200320_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='province_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='cities.Provinces'),
            preserve_default=False,
        ),
    ]
