# Generated by Django 2.2.5 on 2020-03-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0016_routes_province_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directions',
            name='active',
        ),
        migrations.AddField(
            model_name='routes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
