# Generated by Django 2.2.5 on 2020-03-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200322_1813'),
        ('transportations', '0017_auto_20200323_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='employee_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='employees.Employees'),
            preserve_default=False,
        ),
    ]
