# Generated by Django 2.2.5 on 2020-03-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0018_routes_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='cities.Cities'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='employee_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='employees.Employees'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='cities.Provinces'),
        ),
    ]
