# Generated by Django 2.2.5 on 2020-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0020_auto_20200327_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='point_a',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routes',
            name='point_b',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
