# Generated by Django 2.2.5 on 2020-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0021_auto_20200328_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='directions',
            name='vehicle',
            field=models.CharField(max_length=64),
        ),
    ]
