# Generated by Django 2.2.5 on 2020-03-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commuters', '0024_auto_20200327_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferred_Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_a_to_b', models.TimeField()),
                ('tues_a_to_b', models.TimeField()),
                ('wed_a_to_b', models.TimeField()),
                ('thurs_a_to_b', models.TimeField()),
                ('fri_a_to_b', models.TimeField()),
                ('sat_a_to_b', models.TimeField()),
                ('sun_a_to_b', models.TimeField()),
                ('mon_b_to_a', models.TimeField()),
                ('tues_b_to_a', models.TimeField()),
                ('wed_b_to_a', models.TimeField()),
                ('thurs_b_to_a', models.TimeField()),
                ('fri_b_to_a', models.TimeField()),
                ('sat_b_to_a', models.TimeField()),
                ('sun_b_to_a', models.TimeField()),
                ('allowed_route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_time', to='commuters.Allowed_Routes')),
            ],
        ),
    ]
