# Generated by Django 2.2.5 on 2020-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferred_times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferred_times',
            name='fri_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='fri_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='mon_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='mon_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='sat_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='sat_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='sun_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='sun_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='thurs_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='thurs_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='tues_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='tues_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='wed_a_to_b',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferred_times',
            name='wed_b_to_a',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
