# Generated by Django 2.2.5 on 2020-03-22 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0003_auto_20200322_1438'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('job_title', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('present_address', models.CharField(max_length=256)),
                ('permanent_address', models.CharField(max_length=256)),
                ('cell_number', models.CharField(blank=True, max_length=32, null=True)),
                ('tele_number', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='cities.Cities')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
